### PR TITLE
Stub in token support

### PR DESCRIPTION
**Pull request by leetrout**
Opening this PR as I am starting work stubbing in support for a `token` attribute to get the application token inside Terraform.

I'll push changes as I make progress but if y'all aren't interested in accepting this PR please let me know!

### CODE REVIEW

**Comment by PChambino** [comment]
Hi @leetrout, Happy to accept the PR!

I don't know/remember what the `token` attribute is used for, and it doesn't seem we are using it at all in carwow.
And I can't seem to find anything in the docs. Are you able to provide more context about what it is used for as well?

Edit: Actually, I just found it: https://help.hirefire.io/article/52-job-queue-any-programming-language
And we do use it at carwow, but we are copy-pasting the token, so we may also benefit from it.

**Comment by leetrout** [comment]
@PChambino thanks! This should be ready to go.

Go tests passed locally.

Manually tested as well with this TF config:

```hcl
terraform {
  required_providers {
    hirefire = {
      source = "carwow/hirefire"
    }
  }
}

provider "hirefire" {
}

resource "hirefire_organization" "foobar" {
  name      = "foobar"
  time_zone = "UTC"
}

resource "hirefire_account" "foobar" {
  organization_id = hirefire_organization.foobar.id
}

resource "hirefire_application" "foobar" {
  account_id = hirefire_account.foobar.id
  name       = "foobar"
}

output "app-token" {
    value = hirefire_application.foobar.token
    sensitive = true
}
```



image

**Comment by leetrout** [comment]
If you're interested in updating circleci I also have this patch for your config.

```diff
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 5185539..29b58c4 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,7 +58,8 @@ jobs:
             git diff --exit-code go.mod go.sum
       - go/test:
           failfast: true
-          packages: '-v ./...'
+          covermode: atomic
+          race: true

   release:
     parameters:
```

**Comment by PChambino** [comment]
Thanks! I have fixed CircleCI in the main branch.
This looks great!

**Comment by PChambino** [comment]
@leetrout I have released v0.6.0 with the change.
https://github.com/carwow/terraform-provider-hirefire/releases/tag/v0.6.0
Let me know if you find any issues.

**Comment by leetrout** [comment]
Thank you! I will update tomorrow 🙇

**Pull request merged**
